version: 2.0
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      build:
        docker:
           -image: circleci/node:14.16.1

        working_directory: ~/repo

        steps:
          -run: npm install
          -run: npm test
